const CHAT_MODEL = Symbol('CHAT_MODEL');
const WEB_SEARCH_TOOL = Symbol('WEB_SEARCH_TOOL');
const SEND_MAIL_TOOL = Symbol('SEND_MAIL_TOOL');
const CRON_JOB_TOOL = Symbol('CRON_JOB_TOOL');
const TIME_NOW_TOOL = Symbol('TIME_NOW_TOOL');
const ASR_CLIENT = Symbol('ASR_CLIENT');
const REDIS_CLIENT = Symbol('REDIS_CLIENT');
const MILVUS_CLIENT = Symbol('MILVUS_CLIENT');

export {
    CHAT_MODEL, WEB_SEARCH_TOOL, SEND_MAIL_TOOL, CRON_JOB_TOOL, TIME_NOW_TOOL,
    ASR_CLIENT, REDIS_CLIENT, MILVUS_CLIENT
};
